package actions

import (
	"github.com/dkeza/expensesapp/models"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Param)
// DB Table: Plural (params)
// Resource: Plural (Params)
// Path: Plural (/params)
// View Template Folder: Plural (/templates/params/)

// ParamsResource is the resource for the Param model
type ParamsResource struct {
	buffalo.Resource
}

// List gets all Params. This function is mapped to the path
// GET /params
func (v ParamsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	params := &models.Params{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Params from the DB
	if err := q.All(params); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, params))
}

// Show gets the data for one Param. This function is mapped to
// the path GET /params/{param_id}
func (v ParamsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Param
	param := &models.Param{}

	// To find the Param the parameter param_id is used.
	if err := tx.Find(param, c.Param("param_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, param))
}

// New renders the form for creating a new Param.
// This function is mapped to the path GET /params/new
func (v ParamsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Param{}))
}

// Create adds a Param to the DB. This function is mapped to the
// path POST /params
func (v ParamsResource) Create(c buffalo.Context) error {
	// Allocate an empty Param
	param := &models.Param{}

	// Bind param to the html form elements
	if err := c.Bind(param); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(param)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, param))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "param.created.success"))
	// and redirect to the params index page
	return c.Render(201, r.Auto(c, param))
}

// Edit renders a edit form for a Param. This function is
// mapped to the path GET /params/{param_id}/edit
func (v ParamsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Param
	param := &models.Param{}

	if err := tx.Find(param, c.Param("param_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, param))
}

// Update changes a Param in the DB. This function is mapped to
// the path PUT /params/{param_id}
func (v ParamsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Param
	param := &models.Param{}

	if err := tx.Find(param, c.Param("param_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Param to the html form elements
	if err := c.Bind(param); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(param)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, param))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "param.updated.success"))
	// and redirect to the params index page
	return c.Render(200, r.Auto(c, param))
}

// Destroy deletes a Param from the DB. This function is mapped
// to the path DELETE /params/{param_id}
func (v ParamsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Param
	param := &models.Param{}

	// To find the Param the parameter param_id is used.
	if err := tx.Find(param, c.Param("param_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(param); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", T.Translate(c, "param.destroyed.success"))
	// Redirect to the params index page
	return c.Render(200, r.Auto(c, param))
}
